// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQRtduOwEIVOPL8whyIe61AUr8qN4Xnb8',
    appId: '1:518077031734:web:a1aba6dcbba5c81f597f97',
    messagingSenderId: '518077031734',
    projectId: 'blogly-project',
    authDomain: 'blogly-project.firebaseapp.com',
    storageBucket: 'blogly-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdtiXdhfDEMDQqJMqX8yHPCOqcwqDwreQ',
    appId: '1:518077031734:android:656eddfe7715ade1597f97',
    messagingSenderId: '518077031734',
    projectId: 'blogly-project',
    storageBucket: 'blogly-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvTZr90nen4KrpGsgwCSFrCTE8FMSLZjQ',
    appId: '1:518077031734:ios:e22cc661b868434d597f97',
    messagingSenderId: '518077031734',
    projectId: 'blogly-project',
    storageBucket: 'blogly-project.firebasestorage.app',
    iosBundleId: 'com.example.blogly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvTZr90nen4KrpGsgwCSFrCTE8FMSLZjQ',
    appId: '1:518077031734:ios:e22cc661b868434d597f97',
    messagingSenderId: '518077031734',
    projectId: 'blogly-project',
    storageBucket: 'blogly-project.firebasestorage.app',
    iosBundleId: 'com.example.blogly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQRtduOwEIVOPL8whyIe61AUr8qN4Xnb8',
    appId: '1:518077031734:web:8873278370ad5288597f97',
    messagingSenderId: '518077031734',
    projectId: 'blogly-project',
    authDomain: 'blogly-project.firebaseapp.com',
    storageBucket: 'blogly-project.firebasestorage.app',
  );
}
